// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjhdmgjmhhsmuphwbfrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqaGRtZ2ptaGhzbXVwaHdiZnJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1MzA4MzMsImV4cCI6MjA1MzEwNjgzM30.WNU_ORIyzux4osI1F5wBBqHjLEr5TfHPlQkwegFMLvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);